language: r
cache: packages
dist: trusty

before_install:
  - wget https://s3.amazonaws.com/build.pilosa.com/pilosa-master-linux-amd64.tar.gz && tar xf pilosa-master-linux-amd64.tar.gz
  - ./pilosa-master-linux-amd64/pilosa server -d http_data &

r_github_packages:
  - jimhester/covr 

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: Mv3lFHkQvaPt1GAkAtdIsEvW9c0gSHhgLE5rx4u3Ex1gZYdCOFciimT8RcrqUi9EUMZ2xaqPPQYW189PGZFnjvjmuCfOUsXRxMvvZytjcjSagEuNKrRGKLBBXd4pSDqVtZTgTihkOyxfHSWGG7kGvZhan8sCmKNnun7d0BjmmgQ=
